# A TOML plugin for buildifier
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "buildifier"
type = "cli"

[platform.linux]
bin-path = "buildifier"
download-file = "buildifier-linux-{arch}"
checksum-file = "checksums.txt"

[platform.macos]
bin-path = "buildifier"
download-file = "buildifier-darwin-{arch}"
checksum-file = "checksums.txt"

[platform.windows]
bin-path = "buildifier.exe"
download-file = "buildifier-windows-{arch}.exe"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/bazelbuild/buildtools/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/bazelbuild/buildtools"
