# A TOML plugin for jnv:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "jnv"
type = "cli"

[platform.linux]
exe-path = "jnv-{arch}-unknown-linux-gnu/jnv"
download-file = "jnv-{arch}-unknown-linux-gnu.tar.xz"
checksum-file = "jnv-{arch}-unknown-linux-gnu.tar.xz.sha256"

[platform.macos]
exe-path = "jnv-{arch}-apple-darwin/jnv"
download-file = "jnv-{arch}-apple-darwin.tar.xz"
checksum-file = "jnv-{arch}-apple-darwin.tar.xz.sha256"

[platform.windows]
exe-path = "jnv-{arch}-pc-windows-msvc/jnv.exe"
download-file = "jnv-{arch}-pc-windows-msvc.zip"
checksum-file = "jnv-{arch}-pc-windows-msvc.zip.sha256"

[install]
download-url = "https://github.com/ynqa/jnv/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/ynqa/jnv"
