# A TOML plugin for mise:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "mise"
type = "cli"

[platform.linux]
download-file = "mise-v{version}-linux-{arch}"
checksum-file = "SHASUMS256.txt"

[platform.macos]
download-file = "mise-v{version}-macos-{arch}"
checksum-file = "SHASUMS256.txt"

[platform.windows]
download-file = "mise-v{version}-windows-{arch}.zip"
checksum-file = "SHASUMS256.txt"
exe-path = "bin/mise.exe"

[install]
download-url = "https://github.com/jdx/mise/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x64"

[resolve]
git-url = "https://github.com/jdx/mise"
