# A TOML plugin for sentry-cli:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "sentry-cli"
type = "cli"

[resolve]
git-url = "https://github.com/getsentry/sentry-cli"

[platform.linux]
download-file = "sentry-cli-linux-{arch}"

[platform.macos]
download-file = "sentry-cli-Darwin-universal"

[platform.windows]
download-file = "sentry-cli-Windows-{arch}.exe"

[install]
download-url = "https://github.com/getsentry/sentry-cli/releases/download/{version}/{download_file}"

[install.arch]
x86 = "i686"
aarch64 = "arm64"
