# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "k3d"
type = "cli"

[platform.linux]
download-file = "k3d-linux-{arch}"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "k3d-darwin-{arch}"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "k3d-windows-{arch}.exe"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/k3d-io/k3d/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/k3d-io/k3d"
