# A TOML plugin for OpenTofu:
# https://moonrepo.dev/docs/proto/toml-plugin

name = "OpenTofu"
type = "cli"

[platform.linux]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_{os}_{arch}.tar.gz"

[platform.macos]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_darwin_{arch}.tar.gz"

[platform.freebsd]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_{os}_{arch}.tar.gz"

[platform.openbsd]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_{os}_{arch}.tar.gz"

[platform.solaris]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_{os}_{arch}.tar.gz"

[platform.windows]
checksum-file = "tofu_{version}_SHA256SUMS"
download-file = "tofu_{version}_{os}_{arch}.tar.gz"

[install]
checksum-url = "https://github.com/opentofu/opentofu/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/opentofu/opentofu/releases/download/v{version}/{download_file}"

[install.arch]
x86 = "386"
x86_64 = "amd64"
aarch64 = "arm64"

[resolve]
git-url = "https://github.com/opentofu/opentofu"

[detect]
version-files = [".opentofu-version"]
