# A TOML plugin for zellij:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "zellij"
type = "cli"

[platform.linux]
download-file = "zellij-{arch}-unknown-linux-musl.tar.gz"
checksum-file = "zellij-{arch}-unknown-linux-musl.sha256sum"

[platform.macos]
download-file = "zellij-{arch}-apple-darwin.tar.gz"
checksum-file = "zellij-{arch}-apple-darwin.sha256sum"

[install]
download-url = "https://github.com/zellij-org/zellij/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[resolve]
git-url = "https://github.com/zellij-org/zellij"
