# A TOML plugin for k9s:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "k9s"
type = "cli"

[platform.linux]
download-file = "k9s_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "k9s_Darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "k9s_Windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/derailed/k9s/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/derailed/k9s"
