# A TOML plugin for cue:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "CUE"
type = "cli"

[platform.linux]
download-file = "cue_v{version}_linux_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.macos]
download-file = "cue_v{version}_darwin_{arch}.tar.gz"
checksum-file = "checksums.txt"

[platform.windows]
download-file = "cue_v{version}_windows_{arch}.zip"
checksum-file = "checksums.txt"

[install]
download-url = "https://github.com/cue-lang/cue/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/cue-lang/cue"
