name = "Rye"
type = "cli"

[platform.linux]
exe-path = "rye-{arch}-linux"
checksum-file = "rye-{arch}-linux.gz.sha256"
download-file = "rye-{arch}-linux.gz"

[platform.macos]
exe-path = "rye-{arch}-macos"
checksum-file = "rye-{arch}-macos.gz.sha256"
download-file = "rye-{arch}-macos.gz"

[platform.windows]
exe-path = "rye-x86-windows.exe"
checksum-file = "rye-x86-windows.exe.sha256"
download-file = "rye-x86-windows.exe"

[install]
checksum-url = "https://github.com/astral-sh/rye/releases/download/{version}/{checksum_file}"
download-url = "https://github.com/astral-sh/rye/releases/download/{version}/{download_file}"

[resolve]
git-url = "https://github.com/astral-sh/rye"
