name = "Rye"
type = "cli"

[platform.linux]
bin-path = "rye-{arch}-linux"
checksum-file = "rye-{arch}-linux.gz.sha256"
download-file = "rye-{arch}-linux.gz"

[platform.macos]
bin-path = "rye-{arch}-macos"
checksum-file = "rye-{arch}-macos.gz.sha256"
download-file = "rye-{arch}-macos.gz"

[platform.windows]
bin-path = "rye-x86-windows.exe"
checksum-file = "rye-x86-windows.exe.sha256"
download-file = "rye-x86-windows.exe"

[install]
checksum-url = "https://github.com/astral-sh/rye/releases/download/{version}/{checksum_file}"
download-url = "https://github.com/astral-sh/rye/releases/download/{version}/{download_file}"

[install.arch]
aarch64 = "aarch64"
x86_64 = "x86_64"

[install.primary]
exe-path = "rye-{arch}-{os}"

[resolve]
git-url = "https://github.com/astral-sh/rye"
