name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: "${{ matrix.config.target }}"
    runs-on: "${{ matrix.config.os }}"
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-toolchain@v0
        env:
          PROTO_LOG: debug
        with:
          auto-install: true
          cache: false
      - run: moon ci --color
      - uses: appthrust/moon-ci-retrospect@v0
        if: success() || failure()
